[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = ""

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Handle SPA routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

# Disable Next.js plugin
[plugins]
  package = "@netlify/plugin-nextjs"
  enabled = false
