[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "@netlify/functions", "serverless-http"]
  included_files = ["server/**"]

[dev]
  targetPort = 3000
  framework = "vite"
  command = "npm run dev"
  publish = "dist"

[context.production]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }